// Auto-generated by `npx boneyard-js build` — do not edit
// Import this file once in your app entry point
import { registerBones, configureBones } from 'boneyard-js/react'

configureBones({
  color: 'rgba(255,255,255,0.06)',
  darkColor: 'rgba(255,255,255,0.08)',
  animate: 'pulse',
})

registerBones({})
